# Generated by Django 5.1.1 on 2024-09-05 11:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_name', models.CharField(blank=True, max_length=100, null=True)),
                ('account_no', models.IntegerField(blank=True, null=True)),
                ('ifsc', models.CharField(blank=True, max_length=50, null=True)),
                ('account_type', models.CharField(blank=True, max_length=50, null=True)),
                ('branch', models.CharField(blank=True, max_length=100, null=True)),
                ('attachment', models.FileField(blank=True, null=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('branch_name', models.CharField(blank=True, max_length=100, null=True)),
                ('contact', models.IntegerField(blank=True, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('state', models.CharField(blank=True, max_length=100, null=True)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('gst_no', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(blank=True, max_length=100, null=True)),
                ('entity_type', models.CharField(blank=True, choices=[('proprietorship', 'Proprietorship'), ('partnership', 'Partnership'), ('llp', 'LLP'), ('opc', 'OPC'), ('huf', 'HUF'), ('private ltd', 'Private Ltd'), ('Public Limited', 'public limited'), ('trust', 'Trust')], max_length=100, null=True)),
                ('date_of_incorporation', models.DateField(blank=True, null=True)),
                ('contact_person', models.CharField(blank=True, max_length=100, null=True)),
                ('designation', models.CharField(blank=True, max_length=100, null=True)),
                ('contact_no_1', models.IntegerField(blank=True, null=True)),
                ('contact_no_2', models.IntegerField(blank=True, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('business_detail', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='uploads/')),
            ],
        ),
        migrations.CreateModel(
            name='HSNCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hsn_code', models.IntegerField(blank=True, null=True)),
                ('gst_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Owner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner_name', models.CharField(blank=True, max_length=100, null=True)),
                ('share', models.IntegerField(blank=True, default=100, null=True)),
                ('pan', models.CharField(blank=True, max_length=10, null=True)),
                ('aadhar', models.CharField(blank=True, max_length=12, null=True)),
                ('mobile', models.IntegerField(blank=True, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('it_password', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='BranchDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(blank=True, choices=[('ptec', 'PTEC'), ('ptrc', 'PTRC'), ('gst', 'GST'), ('eway', 'EWAY'), ('other', 'OTHER')], max_length=100, null=True)),
                ('login', models.CharField(blank=True, max_length=100, null=True)),
                ('password', models.CharField(blank=True, max_length=100, null=True)),
                ('remark', models.TextField(blank=True, null=True)),
                ('file', models.FileField(blank=True, null=True, upload_to='')),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.branch')),
            ],
        ),
        migrations.AddField(
            model_name='branch',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.client'),
        ),
        migrations.CreateModel(
            name='CompanyDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(blank=True, choices=[('Pan', 'PAN'), ('tan', 'TAN'), ('msme', 'MSME'), ('udym', 'UDYM'), ('mca', 'MCA'), ('pf', 'PF'), ('esic', 'ESIC'), ('other', 'OTHER')], max_length=100, null=True)),
                ('login', models.CharField(blank=True, max_length=100, null=True)),
                ('password', models.CharField(blank=True, max_length=100, null=True)),
                ('remark', models.TextField(blank=True, null=True)),
                ('file', models.FileField(blank=True, null=True, upload_to='')),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.client')),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('gst_no', models.CharField(blank=True, max_length=100, null=True)),
                ('pan', models.CharField(blank=True, max_length=100, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('type', models.CharField(blank=True, choices=[('customer', 'Customer'), ('vendor', 'Vendor')], max_length=100, null=True)),
                ('customer', models.BooleanField(blank=True, null=True)),
                ('vendor', models.BooleanField(blank=True, null=True)),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.client')),
            ],
        ),
        migrations.AddField(
            model_name='client',
            name='mom',
            field=models.ManyToManyField(blank=True, related_name='mom_files', to='api.file'),
        ),
        migrations.AddField(
            model_name='client',
            name='pf',
            field=models.ManyToManyField(blank=True, related_name='pf_files', to='api.file'),
        ),
        migrations.CreateModel(
            name='OfficeLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(blank=True, max_length=100, null=True)),
                ('contact', models.IntegerField(blank=True, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('state', models.CharField(blank=True, max_length=100, null=True)),
                ('country', models.CharField(blank=True, max_length=100, null=True)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.branch')),
            ],
        ),
        migrations.CreateModel(
            name='PurchaseInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attach_invoice', models.FileField(blank=True, null=True, upload_to='')),
                ('attach_e_way_bill', models.FileField(blank=True, null=True, upload_to='')),
                ('utilise_credit', models.BooleanField(blank=True, null=True)),
                ('month', models.DateField(blank=True, null=True)),
                ('invoice_no', models.CharField(blank=True, max_length=100, null=True)),
                ('invoice_date', models.DateField(blank=True, null=True)),
                ('entry_type', models.CharField(blank=True, choices=[('purchase_invoice', 'Purchase_Invoice'), ('credit_note', 'Credit Note'), ('expenses', 'Expenses')], max_length=100, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('unit_of_measure', models.CharField(blank=True, max_length=100, null=True)),
                ('unit', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('rate', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('taxable_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('cgst', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('sgst', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('igst', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('total_invoice_value', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('tds_tcs_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('tds_tcs_section', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('tcs', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('tds', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('amount_receivable', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('client_Location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.officelocation')),
                ('hsn', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.hsncode')),
                ('vendor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.customer')),
            ],
        ),
        migrations.CreateModel(
            name='SalesInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attach_invoice', models.FileField(blank=True, null=True, upload_to='')),
                ('attach_e_way_bill', models.FileField(blank=True, null=True, upload_to='')),
                ('month', models.DateField(blank=True, null=True)),
                ('invoice_no', models.CharField(blank=True, max_length=100, null=True)),
                ('invoice_date', models.DateField(blank=True, null=True)),
                ('invoice_type', models.CharField(blank=True, choices=[('B2B', 'Business to Business'), ('B2C-L', 'Business to Consumer -Local'), ('BSC-O', 'BSC- Other'), ('Nil Rated', 'Nil Rated'), ('Advance Received', 'Advance Received'), ('Export', 'Export'), ('Unregistered local', 'Unregistered Local')], max_length=100, null=True)),
                ('entry_type', models.CharField(blank=True, choices=[('sales_invoice', 'Sales_Invoice'), ('debit_note', 'Debit Note'), ('income', 'Income')], max_length=100, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('unit_of_measure', models.CharField(blank=True, max_length=100, null=True)),
                ('unit', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('rate', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('taxable_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('cgst', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('sgst', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('igst', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('total_invoice_value', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('tds_tcs_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('tds_tcs_section', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('tcs', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('tds', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('amount_receivable', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('client_Location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.officelocation')),
                ('cutomer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.customer')),
                ('hsn', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.hsncode')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=100, null=True)),
                ('last_name', models.CharField(blank=True, max_length=100, null=True)),
                ('ca_admin', models.BooleanField(blank=True, null=True)),
                ('ca_user', models.BooleanField(blank=True, null=True)),
                ('cus_admin', models.BooleanField(blank=True, null=True)),
                ('cus_user', models.BooleanField(blank=True, null=True)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.client')),
            ],
        ),
    ]
