# Generated by Django 5.1.1 on 2024-09-12 05:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='type',
        ),
    ]
