# Generated by Django 5.1.1 on 2024-09-12 05:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_customer_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='branch',
            old_name='company',
            new_name='client',
        ),
    ]
