# Generated by Django 5.1.1 on 2024-09-13 09:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_rename_company_branch_client'),
    ]

    operations = [
        migrations.CreateModel(
            name='IncomeTaxDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(blank=True, choices=[('26AS', 'Form 26AS'), ('FORM_16', 'Form 16'), ('BANK_STATEMENT', 'Bank Statement')], max_length=100, null=True)),
                ('financial_year', models.IntegerField(blank=True, null=True)),
                ('month', models.DateField(blank=True, null=True)),
                ('attachment', models.FileField(blank=True, null=True, upload_to='')),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.client')),
            ],
        ),
        migrations.CreateModel(
            name='PF',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_code', models.CharField(blank=True, max_length=100, null=True)),
                ('employee_name', models.CharField(blank=True, max_length=100, null=True)),
                ('uan', models.CharField(blank=True, max_length=100, null=True)),
                ('pf_number', models.CharField(blank=True, max_length=100, null=True)),
                ('pf_deducted', models.BooleanField(blank=True, null=True)),
                ('date_of_joining', models.DateField(blank=True, null=True)),
                ('status', models.CharField(blank=True, max_length=100, null=True)),
                ('month', models.DateField(blank=True, null=True)),
                ('gross_ctc', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('basic_pay', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('hra', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('statutory_bouns', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('special_allowance', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('pf', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('gratutiy', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('total_gross_salary', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('number_of_days_in_month', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('present_days', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('lwp', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('leave_adjustment', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('gender', models.CharField(blank=True, max_length=100, null=True)),
                ('basic_pay_monthly', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('hra_monthly', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('statutory_bonus_monthly', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('special_allowance_monthly', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('total_gross_salary_monthly', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('provident_fund', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('professional_tax', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('advance', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('esic_employee', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('tds', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('total_deduction', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('net_pay', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('advance_esic_employer_cont', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pf_files', to='api.client')),
            ],
        ),
    ]
