# Generated by Django 5.1.1 on 2024-09-14 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_incometaxdocument_pf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='entity_type',
            field=models.CharField(blank=True, choices=[('proprietorship', 'Proprietorship'), ('partnership', 'Partnership'), ('llp', 'LLP'), ('opc', 'OPC'), ('huf', 'HUF'), ('private ltd', 'Private Ltd'), ('public limited', 'Public Limited'), ('trust', 'Trust')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='incometaxdocument',
            name='document_type',
            field=models.CharField(blank=True, choices=[('26as', '26AS'), ('form_16', 'FORM 16'), ('bank_statement', 'BANK_STATEMENT')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='salesinvoice',
            name='invoice_type',
            field=models.CharField(blank=True, choices=[('b2b', 'B2B'), ('b2c-l', 'B2C-L'), ('bsc-o', 'BSC-O'), ('nil rated', 'Nil Rated'), ('advance received', 'Advance Received'), ('export', 'Export'), ('unregistered local', 'Unregistered Local')], max_length=100, null=True),
        ),
    ]
